apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-05-27T16:17:43Z"
    generation: 1
    labels:
      app: node-leo
    name: node-leo
    namespace: leonel
    resourceVersion: "61851"
    uid: ac2558d6-a5ad-4a59-adf6-95d6ba405be1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: node-leo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: node-leo
      spec:
        containers:
        - image: leonel/node
          imagePullPolicy: Always
          name: node
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2022-05-27T16:17:43Z"
      lastUpdateTime: "2022-05-27T16:17:43Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2022-05-27T16:17:43Z"
      lastUpdateTime: "2022-05-27T16:17:43Z"
      message: ReplicaSet "node-leo-56b475c55c" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
