apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-service
  name: node-service
  namespace: elvis-arispe
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000

  selector:
    app: node
  type: NodePort
status:
  loadBalancer: {}