apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
  namespace: elvis-arispe
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          livenessProbe:
            httpGet:
                path: /
                port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
                path: /
                port: 27017
            initialDelaySeconds: 1
            periodSeconds: 10
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD