apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: secrets
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: $(MONGO_INITDB_ROOT_USERNAME)
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: $(MONGO_INITDB_ROOT_PASSWORD)
      volumes:
        - name: secrets
          secret:
            secretName: db-credentials
            optional: false
